scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.13
    max_x: 0.13
    min_y: -0.14
    max_y: 0.14
    min_z: -1.0
    max_z: 1.0



   # min_x: -13.0
   #  max_x: 13.0
   #  min_y: -14.0
   #  max_y: 14.0
   #  min_z: -1.0
   #  max_z: 1.0